# Generated by Django 5.0.2 on 2024-03-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
