# Generated by Django 5.0.2 on 2024-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_bid',
            field=models.FloatField(max_length=12),
        ),
    ]
