# Generated by Django 5.0.2 on 2024-03-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
