# Generated by Django 5.0.2 on 2024-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
